CPP_PROCESS_FILE = "./main_nodb.out"
TOTAL_ITERATIONS = "10000"
CPP_INPUT_FILE = "./inputFile.json"
DATABASE_FILE = "./AfterHours.db"
ALL_MINIONS_FILE = "./minions.json"
SITE_INPUT_FILE = "./minionsList.json"
TEST_DATA_INPUT_FILE = "./minionsList_test_kripp.json"
